### ISSUE TITLE
跑起来没啥变化呀

### ISSUE THREAD

**Issue by Mikejinhua** [hont127/Image-Rec-Base-unity-shader-#1]
跑起来没啥变化呀
r: 0
UnityEngine.Debug:Log(Object)
RecTest2:Update() (at Assets/aaa/Image-Rec-Base-unity-shader--master/Example2/RecTest2.cs:66)

**Comment by hont127** [comment]
第二个例子，编辑器内手动拖球

**Comment by Mikejinhua** [comment]
托了也没变化。

**Comment by Mikejinhua** [comment]
![image](https://user-images.githubusercontent.com/4988579/60003866-17cfbc00-969e-11e9-98fa-c6dbcd41b8d2.png)

**Comment by hont127** [comment]
![360截图20190624204626512](https://user-images.githubusercontent.com/10148421/60019801-4b700d80-96c1-11e9-99ae-6eb216c66316.jpg)
测试了下没问题，不行你跑第一个demo，屏幕GUI打印success则为找到颜色。

**Comment by Mikejinhua** [comment]
嗯，那我重新下载下试试。

**Comment by Mikejinhua** [comment]
第一个这样吗
![image](https://user-images.githubusercontent.com/4988579/60065253-db4f9f00-9735-11e9-8b7e-05a845f84ede.png)
是不是unty版本不同的原因。。我的unity 2018.4

**Comment by Mikejinhua** [comment]
![image](https://user-images.githubusercontent.com/4988579/60066231-11425280-9739-11e9-8549-cc8210f61d1d.png)
这脚本代码有点奇怪，53行应该传入brushBall.transform.position吧。你的代码传入的zero。 还有感觉你封装了一个类RealtimeImageStatistics，这个脚本又有commandbuf，是不是重复了忘记删除代码了。

**Comment by hont127** [comment]
我中午装了一个2018.4确实有问题，现在已修复，你再试一下。
53行那个是把球的uv输出到一个rt上，不需要球的世界坐标。

**Comment by Mikejinhua** [comment]
可以用了，非常好的demo
